# ddclient configuration file
#
# For more options, see ddclient(8).
#
# Replace these with your actual DDNS provider details

protocol=dyndns2
use=web, web=checkip.dyndns.com/, web-skip=\"IP Address\"
server=members.dyndns.org # Or your DDNS provider server
login=your_ddns_username # CHANGE THIS
password=your_ddns_password # CHANGE THIS
your-domain.com # CHANGE THIS

